declare function a(e: any): any;
declare function c(e: any): boolean;
declare function u(e: any, n: any): boolean;
declare function l(): Set<any>;
declare function s(e: any): RegExpExecArray;
declare function f(e: any, n: any): boolean;
declare function k(e: any, n: any, t?: {}): void;
declare function p(e: any, n: any): any;
declare function d(): boolean;
declare function g(e: any, n: any, o: any): void;
export { a as G, c as I, u as a, l as b, s as c, f as d, k as e, p as g, d as i, g as s };
